generate/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', WelcomeView.as_view(), name='welcome'),
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('verify/<email_code>/', verify, name='verify'),

    path('generate/', GenerateView.as_view(), name='generate'),
    path('questions/', QuestionsView.as_view(), name='questions'),

    path('generating-status/', GenerateSpinner.as_view(), name='spinner'),
    path('generating-process/', generate_process, name='generating'),
    path('generate-options/json', generate_json, name='json_generate'),
    path('generate-options/json/delete', generate_json_delete, name='delete_json'),

    path('content/<int:content_id>', ContentView.as_view(), name='content'),
    path('change/<int:content_id>', change_questions, name='change_questions'),
    path('archive/', ArchiveView.as_view(), name='archive'),

    path('contact/', ContactView.as_view(), name='contact'),

    # account
    path('account/', AccountView.as_view(), name='account'),
    path('logout/', logout_user, name='logout'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),

    # passwords
    path('password_reset/', ChangePasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', ChangePasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ChangePasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', ChangePasswordResetComplete.as_view(), name='password_reset_complete'),

    # transaction
    path('complete-transation', completeTransation, name='completeTransation'),

    # emails send
    path('send-to-my-email/<int:content_id>', send_to_my_email, name='send_to_my_email'),
    path('send-to-partner-email/<int:content_id>', send_to_partner_email, name='send_to_partner_email'),
]

serenatix/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from serenatix import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generate.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

generate/models.py
import os

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField

from generate.utils_models import generate_reff_code, generate_auth_token
from generate.validators import *

from dotenv import load_dotenv
load_dotenv()

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        '''Create and save a user with the given email, and
        password.
        '''
        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must have is_staff=True.'
            )
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must have is_superuser=True.'
            )

        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(
        unique=True,
        max_length=255,
        blank=False,
    )

    # All these field declarations are copied as-is
    # from `AbstractUser`
    first_name = models.CharField(
        _('first name'),
        max_length=30,
        blank=True,
    )
    last_name = models.CharField(
        _('last name'),
        max_length=150,
        blank=True,
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into '
            'this admin site.'
        ),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be '
            'treated as active. Unselect this instead '
            'of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(
        _('date joined'),
        default=timezone.now,
    )

    # Add additional fields here if needed

    def __str__(self):
        return str(self.email)

    objects = UserManager()

    USERNAME_FIELD = 'email'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    credits_count = models.PositiveIntegerField(default=0)
    partner_email = models.EmailField(null=True, blank=True)
    partner_name = models.CharField(max_length=255, null=True, blank=True)

    not_anonim = models.BooleanField(default=False)

    email_verify = models.BooleanField(default=False)
    email_code = models.CharField(max_length=50, blank=True)
    referral_code = models.CharField(max_length=12, blank=True)

    save_answers = models.JSONField(null=True, default={'answers': ''})

    def __str__(self):
        return self.user.email

    def save(self, *args, **kwargs):
        if not self.referral_code:
            self.referral_code = generate_reff_code()
        super().save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        instance.save()
        Profile.objects.create(user=instance, credits_count=os.environ.get('REGISTER_ADD_CREDITS', 0))
    else:
        try:
            instance.profile.save()
        except:
            pass


class ContentTypes(models.Model):
    title = models.CharField(max_length=255)
    credits = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.title


class Content(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    content_type = models.ForeignKey('ContentTypes', on_delete=models.PROTECT)

    title = models.CharField(max_length=255)
    text = models.TextField()

    prompt = models.TextField()
    answers = models.JSONField()
    content_info = models.JSONField()

    time_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('content', kwargs={'content_id': self.id})


class Questions(models.Model):
    question = models.CharField(max_length=255)
    prompt_text = models.CharField(max_length=255)

    content_type = models.ForeignKey('ContentTypes', on_delete=models.PROTECT)

    is_publish = models.BooleanField(default=False)
    have_answers = models.BooleanField(default=True)

    my_order = models.PositiveSmallIntegerField(default=0, blank=False, null=False, db_index=True)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ['my_order']

class Answers(models.Model):
    answer = models.CharField(max_length=255)
    question = models.ForeignKey('Questions', on_delete=models.CASCADE)

    my_order = models.PositiveSmallIntegerField(default=0, blank=False, null=False, db_index=True)

    def __str__(self):
        return self.answer

    class Meta:
        ordering = ['my_order']


class ContentStyles(models.Model):
    title = models.CharField(max_length=100)
    content_type = models.ForeignKey('ContentTypes', on_delete=models.CASCADE)
    my_order = models.PositiveSmallIntegerField(default=0, blank=False, null=False, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['my_order']


class Tone(models.Model):
    title = models.CharField(max_length=100)

    my_order = models.PositiveSmallIntegerField(default=0, blank=False, null=False, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['my_order']


class Length(models.Model):
    title = models.CharField(max_length=100)

    my_order = models.PositiveSmallIntegerField(default=0, blank=False, null=False, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['my_order']


class Occasion(models.Model):
    title = models.CharField(max_length=100)

    my_order = models.PositiveSmallIntegerField(default=0, blank=False, null=False, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['my_order']


class RelationshipTypes(models.Model):
    title = models.CharField(max_length=100)

    my_order = models.PositiveSmallIntegerField(default=0, blank=False, null=False, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['my_order']



class CreditsBuyPriceAndCount(models.Model):
    credits_count = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=7, decimal_places=2, validators=[validate_positive])

    def __str__(self):
        return str(self.credits_count)


class Transactions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    credits_count = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=7, decimal_places=2, validators=[validate_positive])

    time_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user.email)


class ScriptsHead(models.Model):
    script = models.TextField()

    def __str__(self):
        return self.script

class PromptText(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text


class Banners(models.Model):
    image = models.ImageField(upload_to="img/%Y/%m/%d")

    orientation_choice = [
        ('Horizontal', 'Horizontal'),
        ('Vertical', 'Vertical'),
    ]
    orientation = models.CharField(max_length=50, choices=orientation_choice)

generate/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, SetPasswordForm, \
    PasswordResetForm
from phonenumber_field.formfields import PhoneNumberField

from generate.models import User


class LoginUserForm(AuthenticationForm):
    username = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'auth-input', 'placeholder': 'Email Address'})
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'auth-input', 'placeholder': 'Enter Password'})
    )


class RegisterUserForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'auth-input', 'placeholder': 'First name'})
    )
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'auth-input', 'placeholder': 'Last name'})
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'auth-input', 'placeholder': 'Email Address'})
    )
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'auth-input', 'placeholder': 'Create Password'})
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'auth-input', 'placeholder': 'Confirm Password'})
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')


class GenerateForm(forms.Form):
    content_type = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'select_input-hidden', 'placeholder': 'Content type'})
    )
    relationship_type = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'select_input-hidden', 'placeholder': 'Relationship type'})
    )
    partner_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'generate-input', 'placeholder': 'Partner name'})
    )
    relationship_start_date = forms.IntegerField(
        required=True,
        widget=forms.NumberInput(attrs={"min": "1920"})
    )
    occasion = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'select_input-hidden', 'placeholder': 'Occasion'})
    )
    style = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'select_input-hidden', 'placeholder': 'Style'})
    )
    tone = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'select_input-hidden', 'placeholder': 'Tone'})
    )
    genders = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'select_input-hidden', 'placeholder': 'Gender'})
    )


class AccountForm(forms.Form):
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'generate-input', 'placeholder': 'First name'})
    )
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'generate-input', 'placeholder': 'Last name'})
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'generate-input', 'placeholder': 'Email Address'})
    )

    #partner
    partner_email = forms.CharField(
        required=False,
        widget=forms.EmailInput(attrs={'class': 'generate-input', 'placeholder': 'Partner email'})
    )
    partner_name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'generate-input', 'placeholder': 'Partner name'})
    )


class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'generate-input'})
    )
    new_password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'generate-input'})
    )
    new_password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'generate-input'})
    )


#FORGOT PASSWORD
class ResetPasswordEmail(PasswordResetForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'generate-input', 'placeholder': 'Your email'})
    )

class SetPassword(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'generate-input', 'placeholder': 'New password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'generate-input', 'placeholder': 'Confirm password'}),
    )


class ContactForm(forms.Form):
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'generate-input', 'placeholder': 'First name *'})
    )
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'generate-input', 'placeholder': 'Last name *'})
    )
    subject = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'generate-input', 'placeholder': 'Subject *'})
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'generate-input', 'placeholder': 'Email *'})
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'placeholder': 'Message'})
    )

generate/templates/generate/archive.html
{% extends 'generate/main_base.html' %}
{% load static %}
{% load generate_tags %}

{% block css_styles %}
<link rel="stylesheet" href="{% static 'generate/css/archive.css' %}">
{% endblock %}


{% block main %}
<form class="sorting-archive" method="get">
    <div class="select">
        <button type="button" class="select_header" readonly="true">
            {% if get_items.order_by %}
                <div class="select_current">{{ ordering|get_item:get_items.order_by }}</div>
            {% else %}
                <div class="select_current">Sort by</div>
            {% endif %}
            <img src="{% static 'generate/img/icon/stroke.svg' %}" alt="pass-icon" class="input-icon">
        </button>

        <ol class="select_list">
            {% for i in ordering.items %}
                <li class="select_item" data-value="{{i.0}}">{{i.1}}</li>
            {% endfor %}
        </ol>
        <input type="text" name="order_by" value="{{get_items.order_by}}" class="select_input-hidden">
    </div>

    <button class="magenta-btn">
        Sorting
    </button>
</form>

<div class="archive">
    <div class="archive-title">
        <p>Archive</p>
    </div>
    <table>
        <thead>
            <tr>
                <td>
                    <div>
                        Name
<!--                                        <div class="table-sorting">-->
<!--                                            <a href="#!">-->
<!--                                                <img src="./img/icon/stroke-small.svg">-->
<!--                                            </a>-->
<!--                                            <a href="#!">-->
<!--                                                <img src="./img/icon/stroke-small.svg">-->
<!--                                            </a>-->
<!--                                        </div>-->
                    </div>
                </td>
                <td>
                    <div>
                        Type
<!--                                        <div class="table-sorting">-->
<!--                                            <a href="#!">-->
<!--                                                <img src="./img/icon/stroke-small.svg">-->
<!--                                            </a>-->
<!--                                            <a href="#!">-->
<!--                                                <img src="./img/icon/stroke-small.svg">-->
<!--                                            </a>-->
<!--                                        </div>-->
                    </div>
                </td>
                <td>
                    <div>
                        Date
<!--                                        <div class="table-sorting">-->
<!--                                            <a href="#!">-->
<!--                                                <img src="./img/icon/stroke-small.svg">-->
<!--                                            </a>-->
<!--                                            <a href="#!">-->
<!--                                                <img src="./img/icon/stroke-small.svg">-->
<!--                                            </a>-->
<!--                                        </div>-->
                    </div>
                </td>
            </tr>
        </thead>
        <tbody>
            {% for i in archive %}
                <tr>
                    <td>
                        <a href="{{ i.get_absolute_url }}">
                            {{ i.title }}
                        </a>
                    </td>
                    <td>{{ i.content_type }}</td>
                    <td>{{ i.time_create|date:"j F, Y" }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}


{% block js_scripts %}
<script src="{% static 'generate/js/select.js' %}"></script>
{% endblock %}

generate/templates/generate/contact.html
{% extends 'generate/main_base.html' %}
{% load static %}


{% block css_styles %}
<link rel="stylesheet" href="{% static 'generate/css/contact.css' %}">
{% endblock %}

{% block main %}
<main class="main">
    <form class="contact-us" method="post">
        {% csrf_token %}

        <h2 class="contact-title">
            Contact Us
        </h2>
        <div class="form-desc">
            Say Hello send us your thoughts about our products or share your ideas with our Team!
        </div>

        {% if messages %}
            {% for i in messages %}
                {% if i.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="message-main success-msg">
                        {{ i }}
                    </div>
                {% elif i.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="message-main error-msg">
                        {{ i }}
                    </div>
                {% else %}
                     <div class="message-main">
                        {{ i }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <div class="input-fields">
            <div class="input-row">
                <div class="input_wrap">
                    {{ form.first_name }}
                </div>
                <div class="input_wrap">
                    {{ form.last_name }}
                </div>
            </div>
            <div class="input-row">
                <div class="input_wrap">
                    {{ form.subject }}
                </div>
                <div class="input_wrap">
                    {{ form.email }}
                </div>
            </div>

            <div class="input_wrap">
                {{ form.message }}
            </div>
        </div>

        <button class="blue-btn">
            SEND MESSAGE
        </button>
    </form>
</main>
{% endblock %}

generate/templates/generate/homepage_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name='ir-site-verification-token' value='1812737592'>

    <link rel="shortcut icon" href="{% static 'generate/img/icon/favicon.png' %}" type="image/x-icon">

    <link rel="stylesheet" href="{% static 'generate/css/styles.css' %}">
    {% block css_styles %}
    {% endblock %}

    <script>
        {{SCRIPT}}
    </script>

    <title>{{ title }}</title>
</head>
<body>
    <main>
        <div class="homepage-wrapper">
            <div class="planeta-big">
                <img src="{% static 'generate/img/planeta.jpg' %}" style="width: 100%;">
                <div class="vingette"></div>
            </div>
            <div class="right-sidebar-wrap">
                <div class="right-sidebar">
                    <img src="{% static 'generate/img/logo-with-text-big.svg' %}" class="right-sidebar_logo">
                    <div class="planeta-small">
                        <img src="{% static 'generate/img/planeta.jpg' %}" style="width: 100%;">
                        <div class="vingette"></div>
                    </div>
                    {% block sidebar %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </main>
</body>
<script src="{% static 'generate/js/fontAwesome.js' %}"></script>
{% block js_scripts %}

{% endblock %}
</html>

generate/templates/generate/login.html
{% extends 'generate/homepage_base.html' %}
{% load static %}

{% block css_styles %}
<link rel="stylesheet" href="{% static 'generate/css/login.css' %}">
{% endblock %}


{% block sidebar %}
<div class="blocks">
    <div class="sidebar_block">
        <div class="sidebar_block_wrap">
            <form class="auth" method="post">
                {% csrf_token %}
                <div class="auth-title_wrap">
                    <h2>Login Now!</h2>
                    <a href="{% url 'register' %}">
                        Sign up!
                    </a>
                </div>

                {% if messages %}
                    {% for i in messages %}
                        {% if i.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                            <div class="message success-message">
                                {{ i }}
                            </div>
                        {% elif i.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            <div class="message error-message">
                                {{ i }}
                            </div>
                        {% else %}
                             <div class="message">
                                {{ i }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}

                {% if form.non_field_errors %}
                    <div class="message error-message">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                <div class="auth-inputs">
                    <div class="input_wrap">
                        {{ form.username }}
                        <img src="{% static 'generate/img/icon/email.svg' %}" alt="email-icon" class="input-icon">
                    </div>
                    <div class="input_wrap">
                        {{ form.password }}
                        <img src="{% static 'generate/img/icon/shield-security.svg' %}" alt="pass-icon" class="input-icon">
                    </div>
                </div>

                <div class="auth-actions">
                    <div class="checkbox-info">
                        <input type="checkbox" class="save-info-input" name="remember">
                        <label class="checkbox-desc">Remember me</label>
                    </div>
                    <a href="{% url 'password_reset' %}">Forgot Password?</a>
                </div>

                <button type="submit">Login</button>
            </form>
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="google-link">
                <button><i class="fa-brands fa-google"></i> Login with Google</button>
            </a>
        </div>
    </div>
</div>
</div>
{% endblock %}

generate/templates/generate/questions.html
{% extends 'generate/main_base.html' %}
{% load static %}
{% load generate_tags %}

{% block css_styles %}
<link rel="stylesheet" href="{% static 'generate/css/questions.css' %}">
{% endblock %}


{% block main %}
<main class="main">
    <div class="question-header">
        <div class="quastion-heart">
            <img src="{% static 'generate/img/heart.svg' %}">
            <p class="quastion-count">
                {{start_slide}}/{{ questions|length }}
            </p>
            <p class="quastion-count_desc">
                QUESTION
            </p>
        </div>
    </div>


    <form class="answers" method="post">
        {% csrf_token %}

        <div class="answers-tables">

            {% for i in questions %}
            <div class="answer-wrappper">
                <h2 class="quastion-title">
                    {{ i.question }}
                </h2>
                <div class="answers-table">
                    {% if i.have_answers %}
                        {% for j in i.answers_set.all %}
                            <div class="checkbox-info">
                                {% if j.answer in saved_answers %}
                                    <input type="checkbox" checked name="{{i.id}}" value="{{ j.answer }}" class="save-info-input">
                                {% else %}
                                    <input type="checkbox" name="{{i.id}}" value="{{ j.answer }}" class="save-info-input">
                                {% endif %}
                                <label class="checkbox-desc">{{ j.answer }}</label>
                            </div>
                        {% endfor %}

                        <div class="checkbox-info">
                            <p class="checkbox-desc">Your answer</p>
                        </div>
                        <div class="input_wrap" style="margin-left: 0;">
                            <input type="text" name="{{i.id}}:input" value="{{inputs|get_item_input:i.id}}" class="answer-input" style="width: 95%;" placeholder="Enter any other answer">
                        </div>
                    {% else %}
                        <ul>
                        {% for j in i.answers_set.all %}
                            <li>
                                <span class="checkbox-desc">{{ j.answer }}</span>
                            </li>
                        {% endfor %}
                        </ul>

                        <div class="checkbox-info">
                            <p class="checkbox-desc">Your answer</p>
                        </div>
                        <div class="input_wrap" style="margin-left: 0;">
                            <input type="text" name="{{i.id}}:input" value="{{inputs|get_item_input:i.id}}" class="answer-input" style="width: 95%;" placeholder="Enter any other answer">
                        </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="questions-buttons">
            <div class="slick-buttons">
                <button type="button" class="previous-question">
                    Previous Question
                </button>
                <button type="button" class="next-question">
                    Next Question
                </button>
            </div>
            <div class="send-buttons">
                <button name="save" value="on" class="blue-btn">
                    SAVE
                </button>
                <button id="finish" name="finish" value="on" class="magenta-btn">
                    Finished
                </button>
            </div>
        </div>

    </form>
</main>

<div id="preloader" class="disable-load">
    <div id="loader"></div>
    <p>Generating ...</p>
</div>
{% endblock %}


{% block js_scripts %}
<script src="{% static 'generate/js/fontAwesome.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="{% static 'generate/js/slick.min.js' %}"></script>
<!--<script src="{% static 'generate/js/slider.js' %}"></script>-->
<script src="{% static 'generate/js/generatingText.js' %}"></script>
<script src="{% static 'generate/js/ajaxGenerate.js' %}"></script>
<script src="{% static 'generate/js/questionsEnter.js' %}"></script>
<script>
    var $status = $('.quastion-count');
    var $slickElement = $('.answers-tables');

    $slickElement.slick({
        arrows: true,
        speed: 500,
        // fade: true,
        infinite: false,
        cssEase: 'linear',
        nextArrow: '.next-question',
        prevArrow: '.previous-question',
        draggable: false,
        adaptiveHeight: true,
        initialSlide: {{start_slide|add:"-1"}},
    });

    $slickElement.on('init reInit afterChange', function (event, slick, currentSlide, nextSlide) {
        var i = (currentSlide ? currentSlide : 0) + 1;
        $status.text(i + '/' + slick.slideCount);
    });
</script>
{% endblock %}